import Head from "next/head";
// import Link from "next/link";
import { api } from "~/utils/api";
import {
  SignInButton,
  SignUpButton,
  useUser,
  SignOutButton,
  UserButton,
  UserProfile,
} from "@clerk/nextjs";
import { userAgent } from "next/server";
import { User } from "@clerk/nextjs/dist/types/server";

const CreatePostWizard = () => {
  const { user } = useUser();

  if (!user) return null;

  return <div>
    <img src={user.imageUrl} alt="user profile image"></img>
  </div>
}

// type PostWithUsers = RouterOutputs["posts"]["getAll"][number];

// const PostView = (props: PostWithUsers) => {
//   const {post, author} = props;
//   return (
//     <div>
//       <p>{post}</p>
//       <p>By {author}</p>
//     </div>
//   )
// }

export default function Home() {
  const { isSignedIn, isLoaded } = useUser();

  const { data, isLoading } = api.posts.getAll.useQuery();

  if (!isLoaded) return null;

  if (isLoading) return <div>Loading...</div>

  if (!data) return <div>Something went wrong</div>


  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex justify-center">
        <div className="w-full h-full md:max-w-2xl border-x border-slate-400">
          {!isSignedIn && <SignInButton />}
          {!isSignedIn && <SignUpButton />}
          {!!isSignedIn && <SignOutButton />}

          <div>
            {isSignedIn && <CreatePostWizard/>}
            <UserButton afterSignOutUrl="/" />
          </div>
          <div className="flex flex-col">
            {data?.map(({post, author}) => <div className=" p-8 my-2 overflow-hidden border-4 border-double border-blue-500 shadow sm:rounded-lg" key={post.id}>
              {post.content}
              <img src={author?.imgUrl} alt="author image"/>
              <div>{author?.id}</div>
              </div>)}
          </div> 
        </div>
      </main>
    </>
  );
}
